// pages/index.vue
<template>
  <div>
    <header>
      <h1>didit</h1>
      <p class="description">
        Those who have passed
        <a href="https://www.jitec.ipa.go.jp/"
          >Japan's Information Technology Engineers Examination</a
        >
      </p>
    </header>
    <main>
      <ul class="users">
        <li v-for="userId in userIds" :key="userId">
          <nuxt-link :to="userId" class="passed">{{ userId }}</nuxt-link>
        </li>
      </ul>
    </main>
    <footer>
      <p class="navi"><nuxt-link to="/about">about</nuxt-link></p>
    </footer>
  </div>
</template>

<script>
export default {
  asyncData() {
    const path = require('path')
    const userIds = require
      .context('~/data/', false, /\.json$/)
      .keys()
      .map(function (key) {
        return path.basename(key, '.json')
      })
    return { userIds }
  },

  head() {
    return {
      title: 'didit：情報処理技術者試験の合格者をカッコよく見せるサイト',
      meta: [
        {
          hid: 'description',
          name: 'description',
          content:
            "Those who have passed Japan's Information Technology Engineers Examination",
        },
      ],
    }
  },
}
</script>

// pages/index.tsx
import Head from "next/head";
import Link from "next/link";
import fs from "fs";
import path from "path";
import { GetStaticProps } from "next";
import { InferGetStaticPropsType } from "next";

function Home({ userIds }: InferGetStaticPropsType<typeof getStaticProps>) {
  return (
    <div>
      <Head>
        <title>didit：情報処理技術者試験の合格者をカッコよく見せるサイト</title>
        <meta
          name="description"
          content="Those who have passed Japan's Information Technology Engineers Examination"
        />
      </Head>
      <header>
        <h1>didit</h1>
        <p className="description">
          Those who have passed{" "}
          <a href="https://www.jitec.ipa.go.jp/">
            Japan&apos;s Information Technology Engineers Examination
          </a>
        </p>
      </header>
      <main>
        <ul className="users">
          {userIds.map((userId: any) => (
            <li key={userId}>
              <Link href={"/" + userId}>
                <a className="passed">{userId}</a>
              </Link>
            </li>
          ))}
        </ul>
      </main>
      <footer>
        <p className="navi">
          <Link href="/about">
            <a>about</a>
          </Link>
        </p>
      </footer>
    </div>
  );
}

export const getStaticProps: GetStaticProps = async () => {
  const dataDirectory = path.join(process.cwd(), "data");
  const filenames = fs.readdirSync(dataDirectory);
  const userIds = filenames.map((filename) => {
    return path.basename(filename, ".json");
  });
  return {
    props: { userIds },
  };
};

export default Home;
